// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZgCDUe4L--X1YzfgeK7WM5t_tRXpP0zE',
    appId: '1:516169294989:web:65c12454ff2b30de43eec4',
    messagingSenderId: '516169294989',
    projectId: 'intern-project-6402d',
    authDomain: 'intern-project-6402d.firebaseapp.com',
    storageBucket: 'intern-project-6402d.appspot.com',
    measurementId: 'G-G4SGKEJBVB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlv87ZhlRGFEgDpkijcGijVhxCkOpY_T4',
    appId: '1:516169294989:android:196e70b7d099d49443eec4',
    messagingSenderId: '516169294989',
    projectId: 'intern-project-6402d',
    storageBucket: 'intern-project-6402d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeAkOZq4nitrB09gh5PlomMaMCnsKWh04',
    appId: '1:516169294989:ios:6846ce9b8e4a6dad43eec4',
    messagingSenderId: '516169294989',
    projectId: 'intern-project-6402d',
    storageBucket: 'intern-project-6402d.appspot.com',
    androidClientId: '516169294989-v0jqes19u4667giv2k9mu5jqo4dbgjdf.apps.googleusercontent.com',
    iosClientId: '516169294989-0v9b66qdcptrvlfgj88v83d8ao59er2c.apps.googleusercontent.com',
    iosBundleId: 'com.example.cloneMoneyThunder',
  );
}
